wush978/FlippedTradingClassroom#4
wush978/FlippedTradingClassroom pull request #5
Opened 2016-09-16 15:06 UTC by chengu1024

2016-09-16 16:13 UTC, wush978 commented
根據 <https://ci.appveyor.com/project/wush978/flippedtradingclassroom/build/1.0.1#L306>，`Output`多一個。我看了你的更動後，問題應該在： <https://github.com/wush978/FlippedTradingClassroom/pull/5/files#diff-f8c385aafbdd6e54a7e23813fa02513eL248>

Btw, 我之前的寫法是先編輯 `01-Buy-TSMC/lesson.src.yaml` 在利用 `.transform.R` 裡面的內容轉換為 `01-Buy-TSMC/lesson.yaml` 。這過程中會做一些格式檢查。

2016-09-16 16:16 UTC, wush978 requested changes
根據 https://ci.appveyor.com/project/wush978/flippedtradingclassroom/build/1.0.1#L306，`Output`多一個。我看了你的更動後，問題應該在： https://github.com/wush978/FlippedTradingClassroom/pull/5/files#diff-f8c385aafbdd6e54a7e23813fa02513eL248

我剛剛開啟了自動設定，請一定要確保你的版本可以通過自動測試，或是說明自動測試哪邊有bug，我才能merge喲！

2016-09-16 16:17 UTC, wush978 commented
Btw, 我之前的寫法是先編輯 01-Buy-TSMC/lesson.src.yaml 在利用 .transform.R 裡面的內容轉換為 01-Buy-TSMC/lesson.yaml 。這過程中會做一些格式檢查。

你這裡是直接編輯： `01-Buy-TSMC/lesson.yaml`，所以我覺得你應該沒用到這個功能

2016-09-16 17:09 UTC, wush978 approved these changes

2016-09-16 17:10 UTC, wush978 commented on 01-Buy-TSMC/lesson.yaml
> -- Class: cmd_question
你把一個 cmd_question 變回一個 test 了

2016-09-16 17:12 UTC, wush978 requested changes
我希望能夠在 lesson.src.yaml 上編輯，並且透過 `.transform.R` 的 `transform_all()` 來做轉換。

這是因為之後我編輯也會從 lesson.src.yaml 開始，所以如果你直接改 lesson.yaml 的部份，會造成rollback的狀況（你在lesson.yaml的改動沒有回到lesson.src.yaml上)

2016-09-16 17:12 UTC, wush978 commented on 01-Buy-TSMC/lesson.yaml
> +    如果我們要建立一個長度和`STK.week`的資料數相同的向量，可以用`numeric(nrow(STK.week))`來建立。
感謝你的修正，這樣讀比較通順

2016-09-16 17:15 UTC, wush978 commented on 01-Buy-TSMC/lesson.yaml
> +    `setNames(object = nm, nm)`這個函數可以幫助我們做到這件事，
我覺得這段敘述不清楚耶，理由如下：

- 我們是對向量的元素命名，而不是向量本身
- `nm`突然冒出來，也沒有解釋，可能會造成混淆
- 事實上， `setNames(object = nm, nm)` 會對nm向量以nm命名吧！

2016-09-16 17:15 UTC, wush978 requested changes

2016-09-16 17:16 UTC, chengu1024 commented on 01-Buy-TSMC/lesson.yaml
> -- Class: cmd_question
這裡我把這個程式碼拆成兩段做解釋，所以第一段(numeric(nrow(STK.week)))我想說先不用執行所以變回text，第二段(profit = setNames(numeric(nrow(STK.week)), rownames(STK.week)))直接執行整段code就好。
還是wush覺得要用兩個cmd_question我可以改回來

2016-09-16 17:18 UTC, chengu1024 commented on 01-Buy-TSMC/lesson.yaml
> +    如果我們要建立一個長度和`STK.week`的資料數相同的向量，可以用`numeric(nrow(STK.week))`來建立。
不會！謝謝！

2016-09-16 17:26 UTC, chengu1024 commented on 01-Buy-TSMC/lesson.yaml
> +    `setNames(object = nm, nm)`這個函數可以幫助我們做到這件事，
修改成：
    命名向量中的元素，可以幫助我們在之後存取資料時方便許多。
    `setNames()`這個函數可以幫助我們做到這件事，
    第一個參數放入欲命名的向量，第二個參數放入向量元素的名稱。
會好一些嗎？

2016-09-16 17:34 UTC, wush978 commented on 01-Buy-TSMC/lesson.yaml
> +    `setNames(object = nm, nm)`這個函數可以幫助我們做到這件事，
我覺得清楚很多

2016-09-16 17:35 UTC, wush978 commented on 01-Buy-TSMC/lesson.yaml
> -- Class: cmd_question
就照你的判斷吧

2016-09-17 08:49 UTC, wush978 approved these changes

2016-09-17 08:49 UTC, merged